//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsuCorpTest.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IsuCorpTest.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Favorite.
        /// </summary>
        public static string ADD_FAVORITES {
            get {
                return ResourceManager.GetString("ADD_FAVORITES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter value for this field .
        /// </summary>
        public static string ATTRIBUTE_REQUIRED {
            get {
                return ResourceManager.GetString("ATTRIBUTE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESERVATION LIST.
        /// </summary>
        public static string BACK_TO_LIST {
            get {
                return ResourceManager.GetString("BACK_TO_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Date.
        /// </summary>
        public static string BIRTH_DATE {
            get {
                return ResourceManager.GetString("BIRTH_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Name....
        /// </summary>
        public static string CONTACT_NAME {
            get {
                return ResourceManager.GetString("CONTACT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Type.
        /// </summary>
        public static string CONTACT_TYPE_NAME {
            get {
                return ResourceManager.GetString("CONTACT_TYPE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE RESERVATION.
        /// </summary>
        public static string CREATE_RESERVATION_BUTTON {
            get {
                return ResourceManager.GetString("CREATE_RESERVATION_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Reservation.
        /// </summary>
        public static string CREATE_RESERVATION_LABEL {
            get {
                return ResourceManager.GetString("CREATE_RESERVATION_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mm/dd/yyyy.
        /// </summary>
        public static string DATE_FORMAT {
            get {
                return ResourceManager.GetString("DATE_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE.
        /// </summary>
        public static string DELETE_BOTTON {
            get {
                return ResourceManager.GetString("DELETE_BOTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDIT.
        /// </summary>
        public static string EDIT_BOTTON {
            get {
                return ResourceManager.GetString("EDIT_BOTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Reservation.
        /// </summary>
        public static string EDIT_RESERVATION {
            get {
                return ResourceManager.GetString("EDIT_RESERVATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Alphabetic Ascending.
        /// </summary>
        public static string ORDER_BY_ALPHABETIC_ASCENDING {
            get {
                return ResourceManager.GetString("ORDER_BY_ALPHABETIC_ASCENDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Alphabetic Descending.
        /// </summary>
        public static string ORDER_BY_ALPHABETIC_DESCENDING {
            get {
                return ResourceManager.GetString("ORDER_BY_ALPHABETIC_DESCENDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Date Ascending.
        /// </summary>
        public static string ORDER_BY_DATE_ASCENDING {
            get {
                return ResourceManager.GetString("ORDER_BY_DATE_ASCENDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Date Descending.
        /// </summary>
        public static string ORDER_BY_DATE_DESCENDING {
            get {
                return ResourceManager.GetString("ORDER_BY_DATE_DESCENDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Ranking.
        /// </summary>
        public static string ORDER_BY_RANKING {
            get {
                return ResourceManager.GetString("ORDER_BY_RANKING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string PHONE {
            get {
                return ResourceManager.GetString("PHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranking.
        /// </summary>
        public static string RANKING {
            get {
                return ResourceManager.GetString("RANKING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This fild is required.
        /// </summary>
        public static string REQUIRED {
            get {
                return ResourceManager.GetString("REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservations List.
        /// </summary>
        public static string RESERVATION_LIST {
            get {
                return ResourceManager.GetString("RESERVATION_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string SEND_BUTTON {
            get {
                return ResourceManager.GetString("SEND_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ◄ Create Reservation.
        /// </summary>
        public static string SMALL_CREATE_RESERVATION {
            get {
                return ResourceManager.GetString("SMALL_CREATE_RESERVATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ◄ Reservation List.
        /// </summary>
        public static string SMALL_RESERVATION_LIST {
            get {
                return ResourceManager.GetString("SMALL_RESERVATION_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort By.
        /// </summary>
        public static string SORT_BY {
            get {
                return ResourceManager.GetString("SORT_BY", resourceCulture);
            }
        }
    }
}
